version: "3"
services:
  db:
    image: postgres:15.1
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auto-service:
    build: ./auto-service
    container_name: auto-service
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres?currentSchema=auto-service
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8081:8081"
    depends_on:
      - db

  driver-service:
    build: ./driver-service
    container_name: driver-service
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres?currentSchema=driver-service
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8082:8082"
    depends_on:
      - db

  main-service:
    build: ./main-service
    container_name: main-service
    ports:
      - "8080:8080"

volumes:
  pgdata: