openapi: 3.0.0
info:
  title: Main Service - OpenAPI 1.0
  version: 1.0.0
servers:
  - url: http://localhost:8080/
tags:
  - name: User
    description: User API
  - name: Account
    description: Account API
paths:

  /api/v1/account:
    post:
      operationId: registrationAccount
      summary: Registration Account
      tags:
        - Account
      requestBody:
        description: Account DTO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRegistrationRequest'
        required: true
      responses:
        '201':
          description: Created account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          description: Invalid request
        '404':
          description: Resource not found
        '405':
          description: Method is not available
        '500':
          description: Server error

components:
  schemas:
    AccountRegistrationRequest:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
        pin:
          type: number
        user:
          $ref: '#/components/schemas/UserRegistrationRequest'

    UserRegistrationRequest:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
        snils:
          type: string
        inn:
          type: string

    AccountResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
