spring:
  application:
    name: driver-service
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    #    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=driver_service
    url: jdbc:postgresql://db:5432/postgres?currentSchema=driver_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    liquibase-schema: driver_service
    enabled: true

server:
  port: 8082

grpc:
  server:
    port: 9090
